# Permalinks
#
permalink:           pretty

# Setup
title:               Phylogenetic Comparative Methods
tagline:             'A book about pcms'
description:         'An introduction to phylogenetic comparative methods.'
url:                 http://lanyon.getpoole.com
baseurl:             '/pcm'
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
