# Permalinks
#
permalink:           pretty

# Setup
title:               Phylogenetic Comparative Methods
tagline:             'learning from trees'
description:         'An introduction to phylogenetic comparative methods.'
url:                 http://lanyon.getpoole.com
baseurl:             '/pcm'
paginate:            5
github.repo:         https://github.com/lukejharmon/pcm/

# About/contact
author:
  name:              Luke Harmon
  url:               http://lukejharmon.github.io/
  email:             lukeh@uidaho.edu

# Custom vars
version:             1.0.0

# Gems

# github settings
github:
  repo:             https://github.com/lukejharmon/pcm
