# Permalinks
#
permalink:           pretty

# Setup
title:               Phylogenetic Comparative Methods
tagline:             'learning from trees'
description:         'An introduction to phylogenetic comparative methods.'
url:                 http://lanyon.getpoole.com
baseurl:             '/pcm'
paginate:            5
github.repo:         https://github.com/lukejharmon/pcm/

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
#gems: [ 'jekyll-pandoc-multiple-formats' ]

# github settings
github:
  repo:             https://github.com/lukejharmon/pcm

# pandoc - to make multiple versions including pdf

#pandoc:
  # skip: false
  # impose: false
  # output: ./tmp
  # flags: '--smart'
  # site_flags:
  # outputs:
  #   pdf: '--latex-engine=pdflatex --toc'
  #   epub:
  #   markdown:
